Only USDC Carousel
Alcancia-io/Alcancia-FrontEnd pull request #186
Opened 2023-11-02 18:39 UTC by AlbertoMorillo

## Summary
_Briefly describe your changes. Please also include relevant motivation and context_

## Requirements
Carousel balance shows USDC only.

## Type of change
- [ ] feature
- [ ] hotfix
- [ *] fix
- [ ] refactor
- [ ] chore
- [ ] docs

## How to test?
_describe the steps the reviewer should follow to test your changes_
- _eg Run the app, login, go to dashboard..._

## How has this been tested?
_list the test you performed to test your changes_

- [ ] _eg balance should display 0 for new users_
- [ ] Test B
- [ ] Test C

## Screenshots
_add screenshots if need it_

## Checklist (for the reviewer)

- [ ] Does the code compile without errors or warnings?
- [ ] Does the PR is free of merge conflicts?
- [ ] Does the UI is responsive?
- [ ] Is the PR modular?

2023-11-02 18:41 UTC, DHurtado714-itesm reviewed
No esta mejor comentar la parte de `totalBalanceItem` para que en dado caso que se implemente un nuevo token en un futuro, no tengamos que re hacerlo

2023-11-02 18:47 UTC, AlbertoMorillo commented on lib/src/shared/components/dashboard/balance_carousel.dart
@DHurtado714-itesm listo.

2023-11-06 23:35 UTC, kiwis08 requested changes
Tambien se debe quitar en el query de getWalletBalance todos los demas y dejar solo USDC, igual donde hacemos el parse (el fromMap) ya nomas debe tomar en cuenta USDC y no lo otro. Realmente nos quedariamos con un objecto Balance que adentro solo tiene usdc, pero esta bien dejarlo asi por si luego se vuelve a meter otra moneda y nos ahorramos tanto cambio en el codigo

2023-11-07 15:50 UTC, AlbertoMorillo commented
"Realmente nos quedariamos con un objecto Balance que adentro solo tiene usdc, pero esta bien dejarlo asi por si luego se vuelve a meter otra moneda y nos ahorramos tanto cambio en el codigo". Con esta ultima oracion no entendí, lo dejo así o lo comento también?

2023-11-08 01:18 UTC, kiwis08 approved these changes

2023-11-08 01:18 UTC, merged