Fix: zendesk logout
Alcancia-io/Alcancia-FrontEnd pull request #216
Opened 2024-01-08 17:55 UTC by kiwis08

## Summary
_Briefly describe your changes. Please also include relevant motivation and context_

## Requirements
_list any dependencies necessary to review the changes_
- _eg. make sure you reaplace your `.env` with the latest version_

## Type of change
- [ ] feature
- [ ] hotfix
- [x] fix
- [ ] refactor
- [ ] chore
- [ ] docs

## How to test?
_describe the steps the reviewer should follow to test your changes_
- _eg Run the app, login, go to dashboard..._

## How has this been tested?
_list the test you performed to test your changes_

- [ ] _eg balance should display 0 for new users_
- [ ] Test B
- [ ] Test C

## Screenshots
_add screenshots if need it_

## Checklist (for the reviewer)

- [ ] Does the code compile without errors or warnings?
- [ ] Does the PR is free of merge conflicts?
- [ ] Does the UI is responsive?
- [ ] Is the PR modular?

2024-01-08 17:58 UTC, SilvioArzeno commented
@kiwis08 Please add Summary, How to Test el How this has been tested and maybe add a section for "Impacted Features" and put Zendesk under it. Nice PR Template btw. I will indeed steal it for future use

2024-01-08 20:35 UTC, SilvioArzeno requested changes
Check out the comments I left on the review

2024-01-08 20:35 UTC, SilvioArzeno commented on lib/src/features/user-profile/presentation/user_profile_screen.dart
> +      ZendeskMessaging.logoutUser().onError((error, stacktrace) => debugPrint('Error logging out of Zendesk: ${error.toString()}'));
You can use safePrint here as well

2024-01-08 20:50 UTC, SilvioArzeno commented on lib/main.dart
> +
This safePrint is included in a AWS Package that I will add later on so nvm @kiwis08

2024-01-08 20:50 UTC, SilvioArzeno commented on lib/src/features/user-profile/presentation/user_profile_screen.dart
> +      ZendeskMessaging.logoutUser().onError((error, stacktrace) => debugPrint('Error logging out of Zendesk: ${error.toString()}'));
nvm here as well

2024-01-08 21:01 UTC, SilvioArzeno approved these changes
LGTM

2024-01-09 13:42 UTC, AlbertoMorillo approved these changes

2024-01-09 18:20 UTC, merged